### ISSUE TITLE
Permit "nation" "hhs" as geo_types in signal requests

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast#374]
We now include two additional geo types in the covidcast and covidcast_meta endpoints of the Epidata API:
* nation
* hhs

Both clients restrict what geo types are accepted in signal requests, so if someone is looping over metadata results to fetch signal data, they will get e.g.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/sir_complainsalot/delphi_sir_complainsalot/__main__.py", line 12, in <module>
    run_module()  # pragma: no cover
  File "/home/krivard/projects/covid/auto/covidcast-indicators/sir_complainsalot/delphi_sir_complainsalot/run.py", line 28, in run_module
    complaints.extend(check_source(data_source, meta,
  File "/home/krivard/projects/covid/auto/covidcast-indicators/sir_complainsalot/delphi_sir_complainsalot/check_source.py", line 86, in check_source
    latest_data = covidcast.signal(
  File "/home/krivard/projects/covid/auto/covidcast-indicators/sir_complainsalot/env/lib/python3.8/site-packages/covidcast/covidcast.py", line 162, in signal
    raise ValueError("geo_type must be one of " + ", ".join(VALID_GEO_TYPES))   
ValueError: geo_type must be one of state, county, msa, dma, hrr
```

(sorry about this -- I didn't realize it was restricted in the clients. Next time I'll give folks a heads up before we add new geo types)

**Comment by chinandrew** [comment]
Is there urgency to cut a new Python release once #377 is merged? Not sure if any dependencies are currently broken due to this,

**Comment by krivard** [comment]
I have a hack in Sir Complains-a-lot to skip checking all nation and hhs variants, but that's the only thing I know of
